package org.kiirun.joda.beans.model;

import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.kiirun.joda.beans.base.BaseBean;

@BeanDefinition
public class Isbn extends BaseBean implements Bean {
	@PropertyDefinition
	private String isbn;

	public Isbn() {
		super();
	}

	public Isbn( final String isbn ) {
		super();
		this.isbn = isbn;
	}

	@Override
	public String getDisplayName() {
		return isbn;
	}

	// @formatter:off
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code Isbn}.
     * @return the meta-bean, not null
     */
    public static Isbn.Meta meta() {
        return Isbn.Meta.INSTANCE;
    }

    static {
        MetaBean.register(Isbn.Meta.INSTANCE);
    }

    @Override
    public Isbn.Meta metaBean() {
        return Isbn.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the isbn.
     * @return the value of the property
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the isbn.
     * @param isbn  the new value of the property
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Gets the the {@code isbn} property.
     * @return the property, not null
     */
    public final Property<String> isbn() {
        return metaBean().isbn().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public Isbn clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            Isbn other = (Isbn) obj;
            return JodaBeanUtils.equal(getIsbn(), other.getIsbn());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getIsbn());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("Isbn{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("isbn").append('=').append(JodaBeanUtils.toString(getIsbn())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code Isbn}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code isbn} property.
         */
        private final MetaProperty<String> isbn = DirectMetaProperty.ofReadWrite(
                this, "isbn", Isbn.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "isbn");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3241718:  // isbn
                    return isbn;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends Isbn> builder() {
            return new DirectBeanBuilder<>(new Isbn());
        }

        @Override
        public Class<? extends Isbn> beanType() {
            return Isbn.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code isbn} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> isbn() {
            return isbn;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3241718:  // isbn
                    return ((Isbn) bean).getIsbn();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3241718:  // isbn
                    ((Isbn) bean).setIsbn((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
    // @formatter:on
}
